const myArray = [{
        times: "./Images/Iconx.jpg",
        heading: "Tonic ",
        canopy: "CANOPY",
        counter: "",
        back: "Back End Dev",
        year: 2015,
        snapshot: "./Images/SnapshootPortfolio.jpg",
        primarytext: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent",
        html: "html",
        css: "css",
        javs: "javascript",
        seelive: "./Images/live.svg",
        seeliveimg: "./Images/Icon.jpg",
        seesource: "./Images/source.svg",
        seesourceimage: "./Images/Vector.jpg",
    },
    {
        times: "./Images/Iconx.jpg",
        heading: "Multi-Post Sories",
        canopy: "CANOPY",
        counter: "./Images/Counter.jpg",
        back: "Back End Dev",
        year: "2015",
        snapshot: "./Images/SnapshootPortfolio.jpg",
        primarytext: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent",
        html: "html",
        css: "css",
        javs: "javascript",
        seelive: "./Images/live.svg",
        seeliveimg: "./Images/Icon.jpg",
        seesource: "./Images/source.svg",
        seesourceimage: "./Images/Vector.jpg",
    },
    {
        times: "./Images/Iconx.jpg",
        heading: "Tonic ",
        canopy: "CANOPY",
        counter: "./Images/Counter.jpg",
        back: "Back End Dev",
        year: 2015,
        snapshot: "./Images/SnapshootPortfolio.jpg",
        primarytext: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent",
        html: "html",
        css: "css",
        javs: "javascript",
        seelive: "./Images/live.svg",
        seeliveimg: "./Images/Icon.jpg",
        seesource: "./Images/source.svg",
        seesourceimage: "./Images/Vector.jpg",
    },
{
        times: "./Images/Iconx.jpg",
        heading: "Tonic ",
        canopy: "CANOPY",
        counter: "./Images/Counter.jpg",
        back: "Back End Dev",

        times: "./Images/Iconx.jpg",
        heading: "Multi-Post Stories",
        canopy: "CANOPY",
        counter: "./Images/Counter.jpg",
        back: "Back End Dev",
        year: 2015,
        snapshot: "./Images/SnapshootPortfolio.jpg",
        primarytext: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent",
        html: "html",
        css: "css",
        javs: "javascript",
        seelive: "./Images/live.svg",
        seeliveimg: "./Images/Icon.jpg",
        seesource: "./Images/source.svg",
        seesourceimage: "./Images/Vector.jpg",
    },
];

